start setup1.vbs
@echo off
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
start https://youtu.be/uksRrB1XCXU
